config/routes.rb
Rails.application.routes.draw do
	root 'recipes#index'
	
	#Users
	resources :users, only: [:new, :create, :index, :show, :destroy]
	delete '/users/:id' => 'users#destroy', as: 'destroy_user'
	
	#Sessions
	get  '/login'  => 'sessions#new'
	post '/login'  => 'sessions#create'
	get  '/logout' => 'sessions#destroy'
	
	#Omniauth
	get "/auth/:provider/callback" => "sessions#check_omniauth"
	
	#Recipes
	resources :recipes, only: [:new, :create, :index, :show] do
		resources :ingredients, only: [:index]
	end
	delete '/recipes/:id' => 'recipes#destroy', as: 'destroy_recipe'
	
	get '/ingredients' => 'ingredients#index', as: 'ingredients'
	
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
	has_many :recipe_ingredients
	has_many :recipes, through: :recipe_ingredients
	has_many :users, through: :recipes
	
	validates :name, uniqueness: true, presence: true
	
	scope :most_recipes, -> { order('recipe_ingredients_count desc') }
	
	def uses
		recipe_ingredients.count
	end
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
	belongs_to :user
	
	has_many :recipe_ingredients, dependent: :destroy
	has_many :ingredients, through: :recipe_ingredients
	
	validates :name, uniqueness: true, presence: true
	
	accepts_nested_attributes_for :ingredients
	
	scope :by_user, -> (user) { where(user_id: user.id) }
	scope :most_ingredients, -> { order('recipe_ingredients_count desc') }
	
	def ingredients_attributes=(ingredient_attributes)
		ingredient_attributes.values.each do |ingredient_attribute|
			if ingredient_attribute['name'].length > 0
				ingredient = Ingredient.find_or_create_by(ingredient_attribute) 
				self.ingredients << ingredient
			end
		end
	end
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ActiveRecord::Base
	belongs_to :recipe, counter_cache: true
	belongs_to :ingredient, counter_cache: true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	
	has_many :recipes, dependent: :destroy
	has_many :ingredients, through: :recipes
	
	validates :name, uniqueness: true, presence: true
	
	def self.create_with_omniauth(auth)
    create! do |user|
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
			user.password = (0...8).map { (65 + rand(26)).chr }.join #Random String
    end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
	
	helper_method :current_user, :signed_in?
	
	def current_user
		User.find(session[:user_id]) if session[:user_id] && User.exists?(session[:user_id])
	end
	
	def signed_in?
		!!current_user
	end
	
	def auth
    request.env['omniauth.auth']
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
	def index
		unless params[:recipe_id]
			@ingredients = Ingredient.most_recipes
		else
			@ingredients = Recipe.find(params[:recipe_id]).ingredients
		end
	end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
	def index
		@recipes = Recipe.all
	end
	
	def new
		if signed_in?
			@recipe = Recipe.new
		else
			redirect_to root_path, error: 'You need to be signed in to create a recipe'
		end
	end
	
	def create
		@recipe = Recipe.new(recipe_params)
		if @recipe.save
			redirect_to @recipe
		else
			flash[:error] = 'There was an error'
			render :new
		end
	end
	
	def show
		@recipe = Recipe.find(params[:id])
	end
	
	def destroy
		@recipe = Recipe.find(params[:id])
		if @recipe.user == current_user
			@recipe.delete
		end
		
		redirect_to root_path
	end
	
	private
	def recipe_params
		params.require(:recipe).permit(:user_id, :name, :description, ingredient_ids: [], ingredients_attributes: [:name])
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new; end
	
	def create
		user = User.find_by(name: params[:name])
		if user && user.authenticate(params[:password])
			session[:user_id] = user.id
			redirect_to root_path
		else
			redirect_to login_path
		end
	end
	
	def destroy
		session.clear
		redirect_to root_path
	end
	
	def check_omniauth
		if user = User.find_by(uid: auth['uid'])
		else
			user = User.create_with_omniauth(auth)
		end
		
		session[:user_id] = user.id
		redirect_to root_path
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
		@user = User.new
	end
	
	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			redirect_to root_path
		else
			render :new
		end
	end
	
	def index
		@users = User.order('name asc')
	end
	
	def show
		@user = User.find(params[:id])
	end
	
	def destroy
		@user = User.find(params[:id])
		@user.recipes.each do |r|
			r.delete
		end
		@user.delete
		
		redirect_to root_path
	end
	
	private
	def user_params
		params.require(:user).permit(:name, :password)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def flash_alerts
		alerts = []
		alerts << flash[:alert] if flash[:alert]
		alerts << flash[:notice] if flash[:notice]
		alerts << flash[:error] if flash[:error]
		
		return alerts
	end
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
	def delete_rlink recipe
		link_to 'Destroy', destroy_recipe_path(recipe), method: :delete
	end
	
	def recipe_deletable recipe
		delete_rlink recipe if recipe.user == current_user
	end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def showable user
		(link_to user.name, user) if user
	end
	
	def deletable(user)
		if user == current_user
			delete_link user
		end
	end
	
	def delete_link user
		link_to 'Destroy', destroy_user_path(user), method: :delete
	end
end

app/views/ingredients/index.html.erb
<h1>Listing Ingredients</h1>

<ul class='ingredient_description description'>
	<% @ingredients.each do |i| %>
		<li><%= i.name %> | <%= i.uses %> uses</li>
	<% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsAssessment2</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id='wrapper'>
	
	<% if signed_in? %>
		<div class='nav'>
			<nav class='left'>
				<p><%= link_to 'Recipes', recipes_path %></p>
				<p><%= link_to 'Ingredients', ingredients_path %></p>
				<p><%= link_to 'Users', users_path %></p>
			</nav>
			<nav class='right'>
				<p><%= showable current_user %></p>
				<p><%= link_to 'Logout', logout_path %></p>
			</nav>
		</div>	
	<% else %>
		<div class='nav'>
			<nav class='left'>
				<p><%= link_to 'Home', root_path %></p>
				<p><%= link_to 'Sign Up', new_user_path %></p>
				<p><%= link_to 'Login', login_path %></p>
				<p><%= link_to 'Facebook', '/auth/facebook' %></p>
			</nav>
			<nav class='right'>
				<p><a href='https://www.github.com/Buntry'>Site by Parker Griep</a></p>
			</nav>
	<% end %>
	
	<div class='container'>
		<div id='alert_field'>
			<% flash_alerts.each do |alert| %>
				<%= alert %>
			<% end %>
		</div>
		
		<hr>

		<%= yield %>
	</div>
	
</div>

</body>
</html>

app/views/recipes/_form.html.erb
<%= form_for @recipe do |f| %>
	<%= f.hidden_field :user_id, :value => current_user.id %>
	<%= f.label :name %>
	<%= f.text_field :name %> <br>
	<%= f.label :description %> <br>
	<%= f.text_area :description %> <br>
	<%= f.label 'Select Ingredients' %> <br>
	<%= f.collection_select :ingredient_ids, Ingredient.all, :id, :name, {}, {:multiple => true} %> <br>
	<%= f.label 'Custom Ingredients' %> <br>
	<%= f.fields_for :ingredients, 3.times { @recipe.ingredients.build } do |ing_field| %>
		<%= ing_field.text_field :name %> <br>
	<% end %>
	<%= f.submit 'Create Recipe' %>
<% end %>

app/views/recipes/_recipe.html.erb
<li class='recipe_description'>
	<ul>
		<li><strong><%= link_to recipe.name, recipe %></strong> by <%= showable recipe.user %></li>
		<li><%= recipe.description %></li>
	</ul>
</li>

app/views/recipes/index.html.erb
<h1><%= link_to 'Listing Recipes', new_recipe_path %></h1>
<ul class='recipe_list'>
	<%= render @recipes %>
</ul>

app/views/recipes/new.html.erb
<h1>Create a New Recipe</h1>

<%= render 'form' %>

app/views/recipes/show.html.erb
<div class='recipe_header'>
	<h1><%= @recipe.name %></h1>
	<h3 id='recipe_credit'>by <%= showable @recipe.user %></h3>
</div>

<h2>Description</h2>
<p><%= @recipe.description %></p>

<h2><%= link_to 'Ingredient List', recipe_ingredients_path(@recipe) %></h2>
<ul>
	<% @recipe.ingredients.each do |i| %>
	<li><%= i.name %></li>
	<% end %>
</ul>

<%= recipe_deletable @recipe %>

app/views/users/_form.html.erb
<div class='error_field'>
	<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2>
			<%= pluralize(@user.errors.count, "error") %> prohibited this post from being saved:
    </h2>
    <ul class='error_list'>
			<% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
	<% end %>
</div>

<div class='user_form'>
	<%= form_for @user do |f| %>
		<%= f.label :name %>
		<%= f.text_field :name %> <br>
		<%= f.label :password %>
		<%= f.password_field :password %> <br>
		<%= f.submit %>
	<% end %>
</div>

app/views/users/_user.html.erb
<li class='user_description'>
	<%= showable(user) %>
	<%= deletable(user) %>
</li>

app/views/users/index.html.erb
<h1>Listing Users</h1>
<ul class='user_description description'>
	<%= render @users %>
</ul>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<div class='new_user'>
	<%= render 'form' %>
</div>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<h2>Recipes</h2>
<ul>
	<%= render partial: 'recipes/recipe', collection: @user.recipes %>
</ul> 